---
- name: Create sudo user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ user_shell }}"
  become: true

- name: Add ansbile ssh key
  ansible.builtin.authorized_key:
    user: "{{ username }}"
    key: "{{ ansbile_user_public_ssh_key }}"
  become: true