---
- name: Display User Details
  ansible.builtin.include_tasks: display_user_details.yaml

- name: Add User
  ansible.builtin.include_tasks: add_user.yaml

- name: Add User to Sudo 
  ansible.builtin.include_tasks: add_to_sudoers.yaml
