- name: Copy Docker Compose File
  create_storage:
    impersonate_service_account_id: "{{ gcp_impersonate_service_account_id }}"
    project_id: "{{ gcp_project_id }}"
    bucket_name: "{{ gcp_bucket_name }}"
    bucket_location: "{{ gcp_bucket_location }}"
  register: create_storage_result
  failed_when: create_storage_result.rc != "0"

- name: Grant Access to DevOps Group
  bucket_iam_binding:
    impersonate_service_account_id: "{{ gcp_impersonate_service_account_id }}"
    project_id: "{{ gcp_project_id }}"
    iam_service_account: "group:{{ gcp_iam_service_account_id }}"
    iam_role: "{{ gcp_bucket_iam_role }}"
    bucket_name: "{{ gcp_bucket_name }}"
