- name: Install Docker
  hosts: all
  remote_user: '{{ ansible_user }}' # Change remote user to your sudo user!
  become: true
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  roles:
    - role: docker
