---
version: '3.8'

networks:
  discovery:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped

    container_name: uptime-kuma

    networks:
      - discovery   

    volumes:
      - ./uptime-kuma-data:/app/data

    ports:
      - 3001:3001
